### ISSUE TITLE
You entered invalid token

### ISSUE THREAD

**Issue by rjworks** [TeamBixby/DiscordVerify-client#1]
I think everything was setup right, but I keep getting the "You entered invalid token" message on discord when I try to verify using the token I was given in-game.

Discord config:

```
{
  "verify_command": "?verify",
  "bot_token": "mybottoken",
  "password": "mypass",
  "bind_port": 3000,
  "target_host": "127.0.0.1",
  "target_port": 19132,
  "activity_name": "Playing"
} 
```

PocketMine config:

```
address: "127.0.0.1"
port: 19132
password: "mypass"

bindPort: 3001
```

In game:
![image](https://user-images.githubusercontent.com/46464980/108324349-67290100-718d-11eb-86e2-dc3f957f0b73.png)

Discord server:
?verify f6ad7b
*@Me, You entered invalid token*

**Comment by alvin0319** [comment]
Maybe Discord Bot and this plugin is not correctly connected. Can you send a DM?

**Comment by alvin0319** [comment]
`앨빈#0001`

**Comment by rjworks** [comment]
![image](https://user-images.githubusercontent.com/46464980/108331269-38625900-7194-11eb-819d-3f9988dedbbf.png)

**Comment by KadTheHunter** [comment]
I'm having this issue as well, I double checked all settings, and triple checked the spelling of the token given, but it just keeps saying invalid token.

**Comment by rjworks** [comment]
Change bind_port of discord bot to 3001 and pocketmine server to 3000
